In [1]:
from utils import figi_from_ticker, get_shares, figi

from datetime import date

import numpy as np

In [2]:
from strategy import BaseStrategy, MeanReversion

In [3]:
a = MeanReversion("aapl", date(2015, 5, 9), date.today())
a

(1737,)
(1737, 5)


In [18]:
a.exension

array([0.12130153125061141, 0.11585645362217681, 0.11570295574291062, ...,
       0.14870635076789768, 0.1392953311199457, 0.11732022491521255],
      dtype=object)

In [4]:
data = get_shares('aapl')

In [5]:
data['Date'][0]

'1999-12-31'

In [6]:
import os


name = os.path.join("temp", "AAPL.csv")
name

'temp\\AAPL.csv'

In [7]:
os.path.isfile(name)

True

In [8]:
os.path.isfile("temp/AAPL.csv")

True

In [9]:
%%time
history = a.simulation()
history

AttributeError: 'MeanReversion' object has no attribute 'start'

In [10]:
stocks = BaseStrategy("tsla", date(2019, 5, 9), date.today(), days2out=200)
history = stocks.simulation()
history

([['Buy', '2019-05-09', 1, 0.00200080871581676],
  ['Sold', '2019-10-24', 1, 59.93600082397461]],
 0,
 1077.5999755859375)

In [11]:
stocks = BaseStrategy("T", date(2000, 5, 9), date.today(), days2out=200)
history = stocks.simulation()
history

([['Buy', '2000-05-09', 1, 0.03125],
  ['Sold', '2001-02-26', 1, 50.29999923706055]],
 0,
 23.6299991607666)

In [12]:
stocks = BaseStrategy("T", date(2000, 5, 9), date.today(), days2out=1e5)
history = stocks.simulation()
history

([['Buy', '2000-05-09', 1, 0.03125],
  ['Sold', '2002-09-12', 0.1, 24.850000381469727],
  ['Sold', '2020-05-27', 0.1, 31.850000381469727],
  ['Sold', '2020-05-28', 0.1, 31.059999465942383]],
 0.7000000000000001,
 23.6299991607666)

In [13]:
sma = stocks.data

In [14]:
sma = 50
sma_list = []

for i, _ in enumerate(stocks.data):
    sma_list.append(stocks.data[max(i - 50, 0): i + 1, 3].mean())

sma_list = np.array(sma_list)
sma_list

array([48.75      , 47.875     , 46.66666667, ..., 24.16058828,
       24.08843141, 24.02372551])

In [15]:
(stocks.data[:, 3] - sma_list) / sma_list

array([0.0, -0.018276762402088774, -0.05178571428571424, ...,
       -0.000852168551323424, -0.01903122066281815,
       -0.0018201160094704785], dtype=object)

In [16]:
sma_list.append(stocks.data[max(i - 50, 0): i + 1])

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [ ]:
sma_list